### ISSUE TITLE
FR: Display the MDM Server Address

### ISSUE THREAD

**Issue by gmarnin** [munkireport/mdm_status#12]
If the Mac is enrolled in MDM, display the MDM server's DNS address. This will help identify which MDM a Mac is enrolled in. 

[See Rich's script ](https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/check_mdm_enrollment) for sample code.

**Comment by ofirgalcon** [comment]
+1

**Comment by poundbangbash** [comment]
This has been added in version https://github.com/munkireport/mdm_status/tree/v1.13

Update via composer to get the latest code. A new MunkiReport client will need to be generated as the client script has been updated.

**Comment by gmarnin** [comment]
Nice. Thank you!
